### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by barsdeveloper** [francisrstokes/arcsecond#105]
Hello, I am investigating this library as a replacement for Parsimmon (which is now unmantained).
Awesome tool, I initially started using Parsimmon on a web library I am creating because it was very small but this is even smaller and by a large margin, awesome job, thanks.

I am rewriting my Parsimmon grammar and for the most part the concepts are mapped almost one to one but I think I found a different behavior, not sure if it is a bug or a feature.

This is the grammar rule I am referring to specifically smaller
```javascript
static objectEntity = arcsecond.sequenceOf([
    arcsecond.regex(/^Begin\s+Object\s+/),
    arcsecond.sepBy1(arcsecond.whitespace)(
        arcsecond.choice([
            this.customProperty,
            this.createAttributeGrammar(ObjectEntity),
        ])
    ),
    arcsecond.regex(/^\s+End\s+Object/),
]).map(
    ([_0, attributes, _2]) => {
        let values = {}
        attributes.forEach(attributeSetter => attributeSetter(values))
        return new ObjectEntity(values)
    }
)
```

It maps text like the following to some object
```
Begin Object Class=/Script/BlueprintGraph.K2Node_CallFunction Name="K2Node_CallFunction_7"
   FunctionReference=(MemberParent=Class'"/Script/Engine.KismetSystemLibrary"',MemberName="PrintString")
   NodePosX=100
   NodePosY=100
   AdvancedPinDisplay=Shown
   EnabledState=DevelopmentOnly
End Object
```
As you can see I have a starting token (`Begin Object`) and a ending one (`End Object`) In the middle there are entries `SomeAttribute=SomeValue` and this is what the method `createAttributeGrammar` is there for.
```javascript
static createAttributeGrammar(
    entityType,
    valueSeparator = arcsecond.regex(/^\s*=\s*/)
) {
    return arcsecond.sequenceOf([
        this.attributeName,
        valueSeparator,
    ]).chain(([attributeName, _1]) => this
        .grammarFor(entityType.attributes[attributeName], undefined, this.unknownValue)
        .map(attributeValue =>
            values => values[attributeName] = attributeValue
        ))
}
```
Now, the problem comes when arriving at End, it will interpret the `End` using `createAttributeGrammar` but this is fine, it will then look for a `=` and it fails. Now I would expect this: once failed, it would back propagate the failure up, make `sepBy1` from `objectEntity` give up on the current iteration and stop, then try to close the rule using `arcsecond.regex(/^\s+End\s+Object/)`.

Is this expected or a bug?

**Comment by barsdeveloper** [comment]
A possible solution (but still I would like this to be considered as a bug).
```javascript
    static objectEntity = arcsecond.sequenceOf([
        arcsecond.regex(/^Begin\s+Object/),
        arcsecond.many1(
            arcsecond.sequenceOf([
                arcsecond.whitespace,
                arcsecond.choice([
                    this.customProperty,
                    this.createAttributeGrammar(ObjectEntity),
                ])
            ]).map(([_0, entry]) => entry)
        ),
        arcsecond.regex(/^\s+End\s+Object/),
    ]).map(
        ([_0, attributes, _2]) => {
            let values = {}
            attributes.forEach(attributeSetter => attributeSetter(values))
            return new ObjectEntity(values)
        }
    )
```

**Comment by francisrstokes** [comment]
Hi,

I'm not at a computer to dig in further, but I suspect you're hitting the same behaviour as this issue: https://github.com/francisrstokes/arcsecond/issues/98

There is a method for achieving what you're trying to do in that issue, and another open issue to solve the problem more structurally in the library itself at some stage.

**Comment by barsdeveloper** [comment]
Yes, it is the exact same issue, I'm closing. Thanks.
