### ISSUE TITLE
Using possibly() and lookAhead() with endOfInput()

### ISSUE THREAD

**Issue by jeffrose** [francisrstokes/arcsecond#20]
I have a fairly complicated, stateless parser in which I am trying to determine if I am at the end of input in order to make a decision. Using `possibly( endOfInput )` seems to always return `null` and `lookAhead( endOfInput )` seems to be causing an error despite the fact It shouldn't be consuming any input.

Is there a better way to figure this out without introducing state?

**Comment by francisrstokes** [comment]
`endOfInput` returns `null` when successful, and fails when it's not. You can map it to get an actual value:

`possibly(endOfInput.map(() => 'END OF INPUT')`

**Comment by jeffrose** [comment]
That solved it. Thanks!

**Comment by francisrstokes** [comment]
> Maybe endOfInput should return a boolean instead?

Yeah could be, or even just a string `EOF`. I originally didn't consider the overlap between `possibly` and `endOfInput` so I thought null would be OK (since you're not really parsing an actual value - only a conceptual one).
