### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by jeffrose** [francisrstokes/arcsecond#22]
While the way certain parsers are composed makes logical sense, it actually leads to worse performance. I created a simple benchmark comparing `regex( /^[A-Za-z]+/ )` to `letters` and `regex` is significantly faster.

### Test Suite:
```javascript
const
    Benchmark = require( 'benchmark' ),
    { letters, regex } = require( 'arcsecond' ),

    suite = new Benchmark.Suite(),

    reLetters = regex( /^[A-Za-z]+/ ),
    text = 'foobar';

suite
    .add( 'regex', function(){
        reLetters.run( text );
    } )
    .add( 'letters', function(){
        letters.run( text );
    } )
    .on( 'cycle', function( e ){
        console.log( `${ e.target }` );
    } )
    .on( 'complete', function(){
        console.log( `Fastest is ${ this.filter( 'fastest' ).map( 'name' ) }` );
    } )
    .run();
```

### Results:
```
regex x 815,793 ops/sec ±1.69% (86 runs sampled)
letters x 109,446 ops/sec ±0.92% (90 runs sampled)
Fastest is regex
```

Instead of composing `letters` and `digits` out of `letter` and `digit` respectively, consider using `regex` instead.

**Comment by jeffrose** [comment]
The results are similar when comparing `whitespace` to the equivalent regular expression.

### Test Suite:
```javascript
const
    Benchmark = require( 'benchmark' ),
    { whitespace, regex } = require( 'arcsecond' ),

    suite = new Benchmark.Suite(),

    reWhitespace = regex( /^[ \n\t\r]+$/ ),
    text = '     ';

suite
    .add( 'regex', function(){
        reWhitespace.run( text );
    } )
    .add( 'whitespace', function(){
        whitespace.run( text );
    } )
    .on( 'cycle', function( e ){
        console.log( `${ e.target }` );
    } )
    .on( 'complete', function(){
        console.log( `Fastest is ${ this.filter( 'fastest' ).map( 'name' ) }` );
    } )
    .run();
```

### Results:
```
regex x 859,566 ops/sec ±1.27% (86 runs sampled)
whitespace x 131,760 ops/sec ±0.85% (90 runs sampled)
```

**Comment by francisrstokes** [comment]
Hey Jeff,

Wow, this is some great data. I'm not at all opposed to implementing these changes, since they are only internal.

Would you be interested in creating a PR? I'm happy to implement my self but since you've done all the testing perhaps you'd like to add the code?

**Comment by jeffrose** [comment]
Sure. I'll put a PR together later today.

**Comment by francisrstokes** [comment]
Awesome - the only thing to note. is that the error messages shouldn't change because that would technically constitute a breaking change.

So the new implementations should add a `.errorMap()`.

**Comment by jeffrose** [comment]
Are there unit tests for that?
Locally I have the `digits`, `letters`, and `whitespace` unit tests passing. Only `optionalWhitespace` is currently not passing.

**Comment by jeffrose** [comment]
Taking `whitespace` as an example...

The current implementation throws this error:
```javascript
console.log( whitespace.run( '' ).error );
//=> 'ParseError 'many1' (position 0): Expecting to match at least one value'
```

The `regex` based implementation throws this error:
```javascript
console.log( whitespace.run( '' ).error );
//=> 'ParseError (position 0): Expecting string matching '/^\s+/', but got end of input.'
```
The error message has obviously changed but the first error wasn't clear in the first place. A user would have to know that `whitespace` was implemented using `many1` to understand. It likely should have been mapped in the first place. Would you rather remap a `regex` error to a `many1` error or to a new `whitespace` error? It's true this could be seen as a breaking change but it could also be seen as fixing a defect.

```javascript
console.log( whitespace.run( '' ).error );
//=> 'ParseError 'whitespace' (position 0): Expecting to match at least one whitespace value'
```
By the way, it looks like some error messages end in periods and others don't. Is there a preference?

**Comment by francisrstokes** [comment]
> Are there unit tests for that? Locally I have the digits, letters, whitespace, and optionalWhitespace unit tests passing.

No, but according to semantic versioning, a different error message would constitute a major version change, because if someone installs a minor or patch, and was checking the exact error message, their code would break.

The likelihood is pretty small though, but I'd like to stick to a reliable semantic versioning system.

>  It's true this could be seen as a breaking change but it could also be seen as fixing a defect.

I agree! Let's use a mapped error message for now - even if it's not correct - and when a 3.0 release comes one of the goals can be to create decent errors for everything. Sound good?

**Comment by francisrstokes** [comment]
Your pull request closes this issue. I've opened #24 to track things to do for 3.x.
