### ISSUE TITLE
sepBy fails if the separator follows the last item

### ISSUE THREAD

**Issue by stephen-smith** [francisrstokes/arcsecond#26]
```
> Arc.takeLeft(Arc.sepBy(Arc.whitespace)(Arc.letters))(Arc.optionalWhitespace).run("x y z")
{ isError: false,
  result: [ 'x', 'y', 'z' ],
  index: 5,
  data: null }
> Arc.takeLeft(Arc.sepBy(Arc.whitespace)(Arc.letters))(Arc.optionalWhitespace).run("x y z ")
{ isError: true,
  error: 'ParseError (position 6): Expecting letters',
  index: 6,
  data: null }
```

I've got a grammar where the last item is actually parsed differently (but the last separator is the same), so I'm hitting this behavior on a rather large selection of inputs I think should be valid, but since sepBy fails here, I'm currently rejecting them.  Also, the documentation for sepBy (https://github.com/francisrstokes/arcsecond#sepBy) indicates that it would never fail, and it clearly is here.

**Comment by francisrstokes** [comment]
Hey Stephen - interesting issue indeed.

However in this case I don't believe that `sepBy` is working incorrectly (at the very least there is a valid case for both solutions to be correct in some way).

If you match a value and then a separator, and both match correctly, there is an assumption by sepBy that there must be a valid value coming - since it found a valid separator. 

Your example is a trickier because you want your separator to be ignored in this case, but I don't believe the majority of use cases will follow this pattern.

I came up with the following parser that will work in your case. It basically reimplements sepBy using coroutines:

```javascript
const sepByPermissive = sepParser => valParser => coroutine(function* () {
  const results = [];

  const lookAheadSepThenValue = lookAhead(sequenceOf([
    sepParser,
    valParser
  ]));

  while (true) {
    const valueEither = yield either(valParser);
    if (valueEither.isError) {
      return results;
    }
    results.push(valueEither.value);

    // Look ahead and see if there is a separator/value pair coming
    const lookAheadSepValue = yield either(lookAheadSepThenValue);
    if (lookAheadSepValue.isError) {
      // Either no separator, or a separator not followed by a value
      // Return the results without consuming a separator
      return results;
    }

    // If we got here we know there is a separator/value pair coming
    // Consume a separator
    yield sepParser;
  }
});

const whitespaceSeparatedLetters = sepByPermissive(whitespace)(letters);
const parser = sequenceOf([
  whitespaceSeparatedLetters,
  optionalWhitespace,
  digits
])

const res = parser.run('x y z 12345');
// -> [["x", "y", "z"], " ", "12345"]
```

Funnily enough writing this helped me find a bug in `lookAhead` - so this example will work in 2.0.3.

That said, the problem you raised originally is real, but I think it's more of a documentation bug. It should be explained that sepBy can in fact fail in the above circumstances, but not when it fails to match any values.

Thanks for taking the time to show this example and pull request. I will close your open PR, but if you're interested you're welcome to fix the documentation instead.

**Comment by stephen-smith** [comment]
It's your library so, you can make sepBy have whatever semantics you want, but failure-after-greedy-separator would be a divergence from the behavior of Attoparsec, and the parser combinators in GHC Haskell base package:

(base)
```
% ghci
GHCi, version 8.4.4: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/bss/.ghc/ghci.conf
GHCi> import Text.ParserCombinators.ReadP
(0.00 secs, 0 bytes)
GHCi> fst . last $ readP_to_S (sepBy (char 'a') (char ',')) "a,a,a,"
"aaa"
it :: [Char]
(0.01 secs, 64,008 bytes)
```

(attoparsec)
```
% ghci
GHCi, version 8.4.4: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/bss/.ghc/ghci.conf
GHCi> import Data.Attoparsec.Char8
(0.01 secs, 0 bytes)
GHCi> import Data.ByteString.Char8
(0.00 secs, 0 bytes)
GHCi> parseOnly (sepBy (char 'a') (char ',')) (pack "a,a,a,")
Right "aaa"
it :: Either String [Char]
(0.01 secs, 72,264 bytes)
```

To my surprise the original Parsec seems to share your interpretation of sepBy, which I find confusing; there's no more backtracking involved in the version that version I proposed in #27 than in the existing code.

**Comment by stephen-smith** [comment]
BTW, I ended up refactoring my code to avoid using (the greedy) sepBy: https://gitlab.com/boyd.stephen.smith.jr/vue-webpack-ts-lambda/commit/895cfd818aa847e49b1787f6a63ec99d80fe980a?view=parallel

**Comment by francisrstokes** [comment]
> BTW, I ended up refactoring my code to avoid using (the greedy) sepBy

Nice - there's usually a bunch of different ways to express these kinds of things.

> To my surprise the original Parsec seems to share your interpretation of sepBy

This is one of the main reasons I implemented it this way. It's not that I don't think your (and Attoparsec, which I hadn't heard of until now!) is wrong, I just see it as there being two completely valid behaviours - and changing sepBy at this point would be a breaking change. If there's a good way to communicate it without confusion in the docs, I'd be open to including both versions of sepBy in the library.

**Comment by futpib** [comment]
Is there a `sepBy`-like thing that works as expected (leaves the last separator alone for another parser to consume)? Or maybe one can compose something that's already in the library to achieve this?

**Comment by francisrstokes** [comment]
@futpib

> works as expected

Working as expected is kind of in the eye of the beholder :smile: `sepBy` is *values separated by another parser* (i.e. **value** *separator* **value** ...) - so if you encounter a separator, but don't get another value, then you're not matching the pattern you're specifying.

However, what you're describing can be expressed, although it has to do quite a bit of work to make sure it produces the right result:

```javascript
const A = require('.');

const notSepBy = s => x => A.coroutine(function* () {
  const xs = [];

  while (1) {
    // We need to parse at least one `x`
    xs.push(yield x);

    // If we want to preserve the last separator without consuming it,
    // we need to look ahead to see if (a) there is a separator, and
    // (b) there are more results after
    const gotSeparator = yield A.lookAhead(A.possibly(s));
    if (gotSeparator !== null) {
      // Now we need to check for further results
      const gotFurtherResults = yield A.lookAhead(s.chain(() => A.possibly(x)));
      if (gotFurtherResults !== null) {
        // There are more results to come, consume the separator
        yield s;
      } else {
        // No results after separator, return results
        return xs;
      }
    } else {
      // No separator ahead, return results
      return xs;
    }
  }
});

const parser = A.sequenceOf([
  notSepBy(A.char(','))(A.digit),
  A.char(',')
])
const res = parser.run('1,2,');
// -> [[1,2], ',']
```
