### ISSUE TITLE
Overwriting variables

### ISSUE THREAD

**Issue by jeffrose** [francisrstokes/arcsecond#34]
While going through the code I noticed a few values being overwritten which didn't seem intentional.

This line is overwriting `Parser$run` instead of declaring `Parser$fork`.
https://github.com/francisrstokes/arcsecond/blob/master/index.mjs#L64

This line is overwriting `Parser$errorMap` instead of declaring `Parser$errorChain`.
https://github.com/francisrstokes/arcsecond/blob/master/index.mjs#L123

This line is declaring `mapData` instead of `Parser$mapData`...
https://github.com/francisrstokes/arcsecond/blob/master/index.mjs#L157
... which would be okay except this line is declaring `mapData` as well...
https://github.com/francisrstokes/arcsecond/blob/master/index.mjs#L190

**Comment by Avaq** [comment]
These functions are not being overwritten, because these names are local to the function-bodies only. This is because they're *function expressions* rather than *function declarations*.

> The function name. Can be omitted, in which case the function is anonymous. The name is only local to the function body. -- [MDN function expression syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Function#Syntax)

That said, they *are* incorrectly named, and even if that doesn't affect the behaviour of the code, it should probably be fixed. :)

**Comment by francisrstokes** [comment]
You're right @avaq - on both counts. They should be fixed, because right now they're not doing their one job of being helpful for debugging :D

**Comment by francisrstokes** [comment]
@IMax153 your changes are available in `arcsecond@2.0.4`.
