### ISSUE TITLE
Question : Can this be used to create language parsers ?

### ISSUE THREAD

**Issue by gs-akhan** [francisrstokes/arcsecond#36]
Hi,
This might be very basic question. I wanted to know if I can use arcsecond to create language parser for my own DSL and then create an AST out of it. ?
Or I should be looking at some other libraries like JISON to create parser ?
Thanks

**Comment by IMax153** [comment]
Hey @gs-akhan, you can definitely use Arcsecond to create a DSL parser. To manipulate and transform the returned result from parsers, you can use the `.map` method. There are a few examples of the library being used to create AST-like structures in the [examples](https://github.com/francisrstokes/arcsecond/tree/master/examples) directory. 

I have actually been working on a parser for the Lua programming language using this library.

**Comment by francisrstokes** [comment]
Hi there,

Yes this can be used to create language parsers. If you take a look in the examples folder you'll find some languages defined, as well as how the results of parsing are transformed into an ast in different ways.
There is also a tutorials folder which goes over the basics of parser combinators.
