### ISSUE TITLE
Developer Utilities

### ISSUE THREAD

**Issue by IMax153** [francisrstokes/arcsecond#40]
Given that the library is getting more popular and has several contributors now, does it make sense to setup some utilities for development of the library for standardize thing such as linting (ESlint), code style (Prettier), etc? I am happy to create a PR to set these things up if it is something that would be of interest.

**Comment by francisrstokes** [comment]
Completely agree. Big fan of how prettier takes all the discussion out of code styling. My personal preference is to keep linting rules quite relaxed and only complain about potential bugs, and not preferential rules that seem to have made their way into the mainstream.
