### ISSUE TITLE
npm package different versions?

### ISSUE THREAD

**Issue by spenat28** [francisrstokes/arcsecond#59]
How is is possible, that npm repository contains allegedly version 3.1.2 while here in this repository is not any tag with that version?

( https://www.npmjs.com/package/arcsecond )

**Comment by francisrstokes** [comment]
Most likely I merged the latest feature or bugfix, pull it down locally, and ran `npm publish` (which increments package version and adds a git tag) but didn't push that tag back upstream.

**Comment by Avaq** [comment]
> How is is possible

Npm versions and git tags are on no way connected @spenat28. A package maintainer has to perform two separate actions to publish a new version to npm, and to push a new tag to GitHub.

**Comment by spenat28** [comment]
Thanks for explanation. I was not aware of that. I thought that npm uses github as a source and it's just caching it. Not that it has separate copy.
