### ISSUE TITLE
EOF termination

### ISSUE THREAD

**Issue by nikersify** [francisrstokes/arcsecond#7]
Hey,

I've started playing around with `arcsecond` today and noticed that there's no example on how to make the parser fail if not the whole input is matched (even the JSON parser in `examples/` doesn't return an error if, e.g. `{}a` is given into it). I couldn't find a way to do something like:
```js
const eof = /* ? */
const parser = parse(sequenceOf([str('hello'), eof])
parser('hello') // ['hello']
parser('hello world') // should fail
```
Is this possible with the current version?

Thanks in advance, and congrats on the great library - it's a lot of fun!

**Comment by francisrstokes** [comment]
Hey @nikersify , thanks for filing this issue. You're right, EOF was not possible in this version. I've just added and documented the `endOfInput` parser in version 1.3.0.

**Comment by nikersify** [comment]
That was quick, thanks again!
